devices:
  - id: obd_vehicle
    name: OBDlink CX
    source: obd
    obd:
      init_commands:
        - "ATSP7"

    sensors:
      - key: battery_soc_real
        device_class: battery
        unit: "%"
        state_class: measurement
        accuracy_decimals: 1
        mode: "22"
        pid: "028C"
        pre_commands:
          - "ATSH18DA05F1"
          - "ATCRA18DAF105"
        formula: "a*0.39215686"
        update_interval: "10s"
