version: 1

devices:
  - id: "obd_link_cx"
    name: "OBDlink CX"
    source: "obd"

    obd:
      tx_delay: 50ms
      init_commands:
        - "ATSP7"
        - "ATSHFC007B"
        - "ATCP17"
        - "ATCRA17FE007B"
        - "ATFCSH17FC007B"
        - "STCFCPA17FC007B,17FE007B"

    sensors:
      - key: "battery_soc"
        mode: "22"
        pid: "028C"
        decode:
          offset: 0
          length: 1
          type: uint8
          scale: 0.448
          offset_value: -7.16
        unit: "%"
        device_class: battery
        state_class: measurement
        accuracy_decimals: 1
        icon: "mdi:battery-high"
        update_interval: 10s
        pre_commands:
          - "ATSHFC007B"
          - "ATCP17"
          - "ATCRA17FE007B"
          - "ATFCSH17FC007B"
          - "STCFCPA17FC007B,17FE007B"
